trigger:
  - main

variables:
  pythonVersion: '3.11'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(AZURE_SUBSCRIPTION)'
        appName: '$(APP_NAME)'
        package: .