name: Deploy to Azure
on:
  push:
    branches:
      - main
    paths:
      - 'server/**'  # Only trigger on changes in server directory
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: server  # Set default working directory to server
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create startup commands file
      run: |
        echo "pip install -r requirements.txt && gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --timeout 600" > startup.sh
        chmod +x startup.sh
                
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'screen-capture-server'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: server  # Deploy the server directory